### PR TITLE
test: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by joshbDev** [comment]
it's looking like it's failing for Node 5 (possibly because scoped packages weren't supported for 5?), if you wouldn't mind fixing that I'll merge

**Comment by DanielRuf** [comment]
That is because of the old Node.js version. 4 is EOL since today and 5 is not LTS.

**Comment by joshbDev** [comment]
right, would you mind removing the spec from the yaml file then? that way the test will pass and I'll merge 👍

**Comment by DanielRuf** [comment]
Done

**Comment by joshbDev** [comment]
Thanks! Merging

**Pull request merged**
