### PR TITLE
refactor(helpers): provide getMatchingDeclaredPath routine

### PR DESCRIPTION
**Pull request by tsufiev**
The routine was extracted from createObjectFromConfig, and should help
with customized location processing (AKA overwriteLocationHandling).

### CODE REVIEW

**Comment by joshbDev** [comment]
yeah that makes sense, lgtm.

**Comment by tsufiev** [comment]
Awesome, thanks! Would you mind bumping the version and publishing it?

**Comment by joshbDev** [comment]
done

**Comment by joshbDev** [comment]
🤦‍♂️  oops, yeah you're right. I've bumped to 2.0.5 with changes and will put it in the prepublish, thanks for the heads up.

**Pull request merged**
